spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/alura?createDatabaseIfNotExist=true
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect